/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bookstore;

import static bookstore.adminPage.jSplitPane1;
import static bookstore.adminPage.leftPane;
import static bookstore.adminPage.setleftLabelOpaq;
import static bookstore.userProfilePage.contentPanel;
import java.awt.Dialog;
import java.awt.Label;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author detun
 */
public class accountsPage extends javax.swing.JPanel {
    userProfilePage uPage;
    
    /**
     * Creates new form accountsPage
     */
    public accountsPage() {
        initComponents();
        insertAllUser();
//        setCompBackground();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        accountPanel = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        contentPanel = new javax.swing.JPanel();
        userPanel = new javax.swing.JPanel();
        xId = new javax.swing.JLabel();
        username = new javax.swing.JLabel();
        password = new javax.swing.JLabel();
        acctType = new javax.swing.JLabel();
        password1 = new javax.swing.JLabel();
        password2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        addUser = new javax.swing.JButton();

        jLabel3.setText("jLabel3");

        accountPanel.setBackground(Book_Store.getColor(1));
        accountPanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        accountPanel.setMinimumSize(new java.awt.Dimension(997, 529));

        jPanel7.setMinimumSize(new java.awt.Dimension(538, 318));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        contentPanel.setBackground(Book_Store.getColor(0));
        contentPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        contentPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        contentPanel.setLayout(new javax.swing.BoxLayout(contentPanel, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane1.setViewportView(contentPanel);

        userPanel.setBackground(Book_Store.getColor(4)
        );
        userPanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        userPanel.setMaximumSize(new java.awt.Dimension(32767, 36));

        xId.setFont(new java.awt.Font("High Tower Text", 1, 16)); // NOI18N
        xId.setText("No");
        xId.setMaximumSize(new java.awt.Dimension(355, 355));

        username.setFont(new java.awt.Font("High Tower Text", 1, 16)); // NOI18N
        username.setText("Username");
        username.setMaximumSize(new java.awt.Dimension(355, 355));

        password.setFont(new java.awt.Font("High Tower Text", 1, 16)); // NOI18N
        password.setText("Password");
        password.setMaximumSize(new java.awt.Dimension(355, 355));

        acctType.setFont(new java.awt.Font("High Tower Text", 1, 16)); // NOI18N
        acctType.setText("Account type");
        acctType.setMaximumSize(new java.awt.Dimension(355, 355));

        password1.setFont(new java.awt.Font("High Tower Text", 1, 16)); // NOI18N
        password1.setText("Question");
        password1.setMaximumSize(new java.awt.Dimension(355, 355));

        password2.setFont(new java.awt.Font("High Tower Text", 1, 16)); // NOI18N
        password2.setText("Security answer");
        password2.setMaximumSize(new java.awt.Dimension(355, 355));

        javax.swing.GroupLayout userPanelLayout = new javax.swing.GroupLayout(userPanel);
        userPanel.setLayout(userPanelLayout);
        userPanelLayout.setHorizontalGroup(
            userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(xId, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(password1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(password2, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(acctType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        userPanelLayout.setVerticalGroup(
            userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userPanelLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(xId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(username, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(password, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(password1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(password2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(acctType, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 874, Short.MAX_VALUE)
            .addComponent(userPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addComponent(userPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 379, Short.MAX_VALUE))
        );

        jLabel7.setFont(new java.awt.Font("Lucida Handwriting", 1, 18)); // NOI18N
        jLabel7.setText("LOGIN ACCOUNT");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bookstore/increaseA.png"))); // NOI18N
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.E_RESIZE_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        addUser.setBackground(Book_Store.getColor(4)
        );
        addUser.setText("ADD");
        addUser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addUser.setFocusPainted(false);
        addUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addUserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout accountPanelLayout = new javax.swing.GroupLayout(accountPanel);
        accountPanel.setLayout(accountPanelLayout);
        accountPanelLayout.setHorizontalGroup(
            accountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accountPanelLayout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(38, 38, 38)
                .addGroup(accountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(accountPanelLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, accountPanelLayout.createSequentialGroup()
                        .addGroup(accountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(accountPanelLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(addUser))
                            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(59, 59, 59))))
        );
        accountPanelLayout.setVerticalGroup(
            accountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accountPanelLayout.createSequentialGroup()
                .addGroup(accountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(accountPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(addUser)
                .addGap(5, 5, 5))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 997, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, 0)
                    .addComponent(accountPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(0, 0, 0)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 529, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, 0)
                    .addComponent(accountPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(0, 0, 0)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        leftPane.setVisible(!leftPane.isShowing());
        jSplitPane1.updateUI();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void addUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addUserActionPerformed
//        JLabel x = new JLabel()
        
        JDialog userDialog = new JDialog();
        uPage = new userProfilePage(userDialog);
        uPage.setOperation("new user");
        userDialog.add(uPage.contentPanel);
        userDialog.setModalityType(Dialog.ModalityType.APPLICATION_MODAL);
        userDialog.setSize(400,550);
        userDialog.setResizable(false);
        userDialog.setLocationRelativeTo(null);
//        userDialog.setType(Window.Type.POPUP);
        userDialog.setVisible(true);
        contentPanel.updateUI();
        
    }//GEN-LAST:event_addUserActionPerformed

    public static void addContentPanel(JPanel panel){
        contentPanel.add(panel);
        contentPanel.updateUI();
    }
    public static void editContentPanel(int xId,accountPanel panel){
        JPanel user = (JPanel)contentPanel.getComponent(xId);
        contentPanel.remove(user);
        user=new accountPanel().getUserPanel();
        contentPanel.add(panel.getUserPanel(),xId);
        contentPanel.updateUI();
    }
    public static int contentCompCount(){
        System.err.println("cc:"+contentPanel.getComponentCount());
        return contentPanel.getComponentCount();
    }
    
    public static void updateUserId(){
        for(int i=0;i<contentPanel.getComponentCount();i++){
            JPanel user = (JPanel)contentPanel.getComponent(i);
            ((JLabel)user.getComponent(0)).setText(""+(i+1));
            dbConnect.updateRowId("User", ((JLabel)user.getComponent(1)).getText()
                    , i+1);
            
        }
        contentPanel.updateUI();
    }
    
    public static void setCompBackground(){
        accountPanel.setBackground(Book_Store.getColor(1));
        contentPanel.setBackground(Book_Store.getColor(0));
        addUser.setBackground(Book_Store.getColor(4));
        userPanel.setBackground(Book_Store.getColor(4));
    }
    
    public JPanel getPanel(){
        setleftLabelOpaq(1);        
        return accountPanel;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JPanel accountPanel;
    private javax.swing.JLabel acctType;
    public static javax.swing.JButton addUser;
    public static javax.swing.JPanel contentPanel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel password;
    private javax.swing.JLabel password1;
    private javax.swing.JLabel password2;
    public static javax.swing.JPanel userPanel;
    private javax.swing.JLabel username;
    private javax.swing.JLabel xId;
    // End of variables declaration//GEN-END:variables

    public void insertAllUser() {
        ResultSet allUser = dbConnect.selectAll("User");
        if (allUser==null) 
            return;
       
        try {
            allUser.next();
            while (allUser.next()) {
                accountPanel user = new accountPanel(
                    allUser.getInt("xId"),
                    allUser.getString("fullname"),
                    allUser.getString("username"),
                    allUser.getString("password"),
                    allUser.getString("email"),
                    allUser.getInt("secretQuestion"),
                    allUser.getString("secretAnswer"),
                    allUser.getString("acctType"));
                addContentPanel(user.getUserPanel());
                
            }
        } catch (SQLException ex) {
            Logger.getLogger(accountsPage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
