/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bookstore;

import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.border.BevelBorder;
import javax.swing.border.SoftBevelBorder;

/**
 *
 * @author detun
 */
public class bookPanel extends javax.swing.JPanel {
    bookProfilePage bPage;
    private String genre = "sci-fi";
    private int quantity=2;

    /**
     * Creates new form bookPanel
     */
    public bookPanel() {
        initComponents();
    }
    
    public bookPanel(bookPanel book){
        
        initComponents();
         setxId(book.getxId()+"");
        setSerialNo(book.getSerialNo());
        setAuthor(book.getAuthor());
        setBookName(book.getBookName());
        setGenre(book.getGenre());
        setSection(book.getSection());
        setShelf(book.getShelf());
        setQuantity(book.getQuantity());
        setPrice(book.getPrice());
    }
    
    public bookPanel(String xId,String serial,String author,String bookname,String genre,String section,String shelf,Object quantity,String price) {
        initComponents();
        setxId(xId);
        setSerialNo(serial);
        setAuthor(author);
        setBookName(bookname);
        setGenre(genre);
        setSection(section);
        setShelf(shelf);
        setQuantity(quantity);
        setPrice(price);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bookP = new javax.swing.JPanel();
        xId = new javax.swing.JLabel();
        serialNo = new javax.swing.JLabel();
        author = new javax.swing.JLabel();
        shelf = new javax.swing.JLabel();
        deleteBook = new javax.swing.JLabel();
        editBook = new javax.swing.JLabel();
        bookName = new javax.swing.JLabel();
        section = new javax.swing.JLabel();
        price = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(32767, 31));
        setOpaque(false);

        bookP.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bookP.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bookP.setInheritsPopupMenu(true);
        bookP.setMaximumSize(new java.awt.Dimension(32767, 36));
        bookP.setOpaque(false);
        bookP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bookPMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bookPMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bookPMouseExited(evt);
            }
        });
        bookP.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentMoved(java.awt.event.ComponentEvent evt) {
                bookPComponentMoved(evt);
            }
        });

        xId.setFont(new java.awt.Font("Lucida Console", 0, 12)); // NOI18N
        xId.setText("1");
        xId.setMaximumSize(new java.awt.Dimension(355, 355));

        serialNo.setFont(new java.awt.Font("Lucida Console", 0, 12)); // NOI18N
        serialNo.setText("MP15xzAW");
        serialNo.setMaximumSize(new java.awt.Dimension(355, 355));

        author.setFont(new java.awt.Font("Lucida Console", 2, 12)); // NOI18N
        author.setText("John Kennedy");
        author.setMaximumSize(new java.awt.Dimension(355, 355));

        shelf.setFont(new java.awt.Font("Lucida Console", 0, 12)); // NOI18N
        shelf.setText("3");
        shelf.setMaximumSize(new java.awt.Dimension(355, 355));

        deleteBook.setBackground(new java.awt.Color(208, 204, 204));
        deleteBook.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        deleteBook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bookstore/bookdelete.png"))); // NOI18N
        deleteBook.setToolTipText("delete book");
        deleteBook.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deleteBook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteBookMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                deleteBookMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                deleteBookMouseExited(evt);
            }
        });

        editBook.setBackground(new java.awt.Color(208, 204, 204));
        editBook.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        editBook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bookstore/edit (1).png"))); // NOI18N
        editBook.setToolTipText("edit");
        editBook.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        editBook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editBookMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                editBookMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                editBookMouseExited(evt);
            }
        });

        bookName.setFont(new java.awt.Font("Lucida Console", 0, 12)); // NOI18N
        bookName.setText("Adventure Of Sabrina");
        bookName.setMaximumSize(new java.awt.Dimension(355, 355));

        section.setFont(new java.awt.Font("Lucida Console", 0, 12)); // NOI18N
        section.setText("Drama");
        section.setMaximumSize(new java.awt.Dimension(355, 355));

        price.setFont(new java.awt.Font("Lucida Console", 0, 12)); // NOI18N
        price.setText("25000");
        price.setMaximumSize(new java.awt.Dimension(355, 355));

        javax.swing.GroupLayout bookPLayout = new javax.swing.GroupLayout(bookP);
        bookP.setLayout(bookPLayout);
        bookPLayout.setHorizontalGroup(
            bookPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bookPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(xId, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(serialNo, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(author, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(bookName, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(section, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(shelf, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(price, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(editBook, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(deleteBook, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5))
        );
        bookPLayout.setVerticalGroup(
            bookPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bookPLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(bookPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(editBook, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                    .addComponent(xId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(serialNo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(author, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(shelf, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bookName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(section, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(price, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(deleteBook, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bookP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bookP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void deleteBookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteBookMouseClicked

        if(JOptionPane.showConfirmDialog(null, "Are you sure you want to delete?", getBookName(), 0)==JOptionPane.YES_OPTION){
            
            inventoryPage.contentPanel.remove(getxId()-1);
            inventoryPage.contentPanel.updateUI();
            inventoryPage.updateBookId();
            inventoryPage.setSearchPanel();
            inventoryPage.writeJsonFile();
        }
    }//GEN-LAST:event_deleteBookMouseClicked

    private void deleteBookMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteBookMouseEntered
        bookPMouseEntered(evt);
        deleteBook.setOpaque(true);
        bookP.updateUI();
    }//GEN-LAST:event_deleteBookMouseEntered

    private void deleteBookMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteBookMouseExited
        bookPMouseExited(evt);
        deleteBook.setOpaque(false);
        bookP.updateUI();
    }//GEN-LAST:event_deleteBookMouseExited

    private void editBookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editBookMouseClicked
        JDialog bookDialog = new JDialog();
        bPage = new bookProfilePage(
            getxId()-1,
            getSerialNo(),
            getAuthor(),
            getBookName(),
            getGenre(),
            getSection(),
            getShelf(),
            getQuantity(),
            getPrice(),
            bookDialog   );
        bPage.setOperation("edit user");
        bookDialog.add(bPage.contentPanel);
        bookDialog.setModalityType(JDialog.ModalityType.APPLICATION_MODAL);
        bookDialog.setSize(400,550);
        bookDialog.setResizable(false);
        bookDialog.setLocationRelativeTo(null);
        //        userDialog.setType(Window.Type.POPUP);
        bookDialog.setVisible(true);
        this.updateUI();
    }//GEN-LAST:event_editBookMouseClicked

    private void editBookMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editBookMouseEntered
        bookPMouseEntered(evt);
        editBook.setOpaque(true);
        bookP.updateUI();
    }//GEN-LAST:event_editBookMouseEntered

    private void editBookMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editBookMouseExited
        bookPMouseExited(evt);
        editBook.setOpaque(false);
        bookP.updateUI();
    }//GEN-LAST:event_editBookMouseExited

    private void bookPMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookPMouseEntered
        //        userPanel.setBorder(new EtchedBorder(0));
        bookP.setBorder(new BevelBorder(0));
    }//GEN-LAST:event_bookPMouseEntered

    private void bookPMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookPMouseExited
        bookP.setBorder(new SoftBevelBorder(0));
    }//GEN-LAST:event_bookPMouseExited

    private void bookPComponentMoved(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_bookPComponentMoved
//        System.err.println("component moved "+accountsPage.contentPanel.getComponentZOrder(this.userPanel));
    }//GEN-LAST:event_bookPComponentMoved

    private void bookPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookPMouseClicked
        JDialog bookDialog = new JDialog();
        bookDialog.add(new addCheckout(this,bookDialog).getPanel());
        bookDialog.setModalityType(JDialog.ModalityType.APPLICATION_MODAL);
        bookDialog.setSize(248, 220);
        bookDialog.setResizable(false);
//        bookDialog.setLocationRelativeTo(this);
        bookDialog.setLocation(inventoryPage.contentPanel.getComponent(this.getxId()-1).getLocationOnScreen());
        bookDialog.setLocation(bookDialog.getX()+400,bookDialog.getY());
        //        userDialog.setType(Window.Type.POPUP);
        bookDialog.setVisible(true);
    }//GEN-LAST:event_bookPMouseClicked

    public JPanel getPanel(){
        return bookP;
    }
    
    public String getAuthor() {
        return author.getText();
    }

    public void setAuthor(String author) {
        this.author.setText(author);
    }

    public String getBookName() {
        return bookName.getText();
    }

    public void setBookName(String bookName) {
        this.bookName.setText(bookName);
    }

    public String getPrice() {
        return price.getText();
    }

    public void setPrice(String price) {
        this.price.setText(""+price);
    }

    public String getSection() {
        return section.getText();
    }

    public void setSection(String section) {
        this.section.setText(section);
    }

    public String getSerialNo() {
        return serialNo.getText();
    }

    public void setSerialNo(String serialNo) {
        this.serialNo.setText(serialNo);
    }

    public String getShelf() {
        return shelf.getText();
    }

    public void setShelf(String shelf) {
        this.shelf.setText(shelf);
        
    }

    public int getxId() {
        System.err.println("getxid: "+Integer.parseInt(xId.getText()));
        return Integer.parseInt(xId.getText());
    }

    public void setxId(String xId) {
        this.xId.setText(xId);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel author;
    private javax.swing.JLabel bookName;
    private javax.swing.JPanel bookP;
    private javax.swing.JLabel deleteBook;
    private javax.swing.JLabel editBook;
    private javax.swing.JLabel price;
    private javax.swing.JLabel section;
    private javax.swing.JLabel serialNo;
    private javax.swing.JLabel shelf;
    private javax.swing.JLabel xId;
    // End of variables declaration//GEN-END:variables

    public void setQuantity(Object quantity) {
        System.err.println(Integer.parseInt(quantity.toString()));
        
        this.quantity=Integer.parseInt(quantity.toString());
    }
    
    int getQuantity() {
        return quantity;
    }

    public void setGenre(String genre) {
        this.genre=genre;
    }
    
    String getGenre(){
        return genre;
    }
}


