/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bookstore;

import java.awt.Color;
import java.awt.event.KeyEvent;
import java.text.NumberFormat;
import javax.swing.JDialog;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.border.LineBorder;
import javax.swing.text.NumberFormatter;

/**
 *
 * @author detun
 */
public class bookProfilePage extends javax.swing.JPanel {
    
    JDialog bookDialog;
    int compId=-1;
    String serial=null;
    /**
     * Creates new form bookProfilePage
     */
    public bookProfilePage(JDialog bookDialog) {
        initComponents();
        this.bookDialog=bookDialog;
//        NumberFormat longFormat = NumberFormat.getIntegerInstance();
//
//        NumberFormatter numberFormatter = new NumberFormatter(longFormat);
//        numberFormatter.setValueClass(Integer.class); //optional, ensures you will always get a long value
//        numberFormatter.setAllowsInvalid(false); //this is the key!!
//        numberFormatter.setMaximum(8); //Optional
//        quantityField = new JFormattedTextField(numberFormatter);
    }

    bookProfilePage(int componentZOrder, String serialNo, String author, String bookName, String genre, String section, String shelf, int quantity, String price, JDialog bookDialog) {
        this(bookDialog);
        this.compId=componentZOrder;
        setSerialNo(serialNo);
        setAuthor(author);
        setbookName(bookName);
        setGenre(genre);
        setSection(section);
        setShelf(shelf);
        setQuantity(String.valueOf(quantity));
        setPrice(price);
        serial=serialNo;
        dataFieldFilled();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contentPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        quantityField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        authorField = new javax.swing.JTextField();
        clearButton = new javax.swing.JButton();
        SaveButton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        sectField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        serialField = new javax.swing.JTextField();
        operation = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        genreField = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        shelField = new javax.swing.JTextField();
        cancelButton = new javax.swing.JButton();
        priceField = new javax.swing.JFormattedTextField();

        contentPanel.setBackground(new java.awt.Color(254, 254, 246));
        contentPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(51, 51, 51), new java.awt.Color(153, 153, 153), new java.awt.Color(204, 204, 204)));
        contentPanel.setForeground(new java.awt.Color(51, 51, 51));
        contentPanel.setMaximumSize(new java.awt.Dimension(400, 510));
        contentPanel.setMinimumSize(new java.awt.Dimension(400, 510));

        jLabel2.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bookstore/books-stack.png"))); // NOI18N
        jLabel2.setText("BOOK DATA");
        jLabel2.setIconTextGap(10);

        quantityField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantityFieldActionPerformed(evt);
            }
        });
        quantityField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                quantityFieldKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                quantityFieldKeyTyped(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel5.setText("Quantity");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel6.setText("Author");

        authorField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                authorFieldActionPerformed(evt);
            }
        });
        authorField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                authorFieldKeyReleased(evt);
            }
        });

        clearButton.setBackground(new java.awt.Color(204, 204, 204));
        clearButton.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 8)); // NOI18N
        clearButton.setText("Clear");
        clearButton.setToolTipText("Clear all text");
        clearButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        SaveButton.setBackground(new java.awt.Color(204, 204, 204));
        SaveButton.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 10)); // NOI18N
        SaveButton.setText("Save");
        SaveButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SaveButton.setEnabled(false);
        SaveButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        SaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveButtonActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel7.setText("Section");

        sectField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sectFieldActionPerformed(evt);
            }
        });
        sectField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                sectFieldKeyReleased(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel10.setText("Book Name");

        nameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameFieldActionPerformed(evt);
            }
        });
        nameField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nameFieldKeyReleased(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel11.setText("Serial No");

        serialField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serialFieldActionPerformed(evt);
            }
        });
        serialField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                serialFieldKeyReleased(evt);
            }
        });

        operation.setBackground(new java.awt.Color(93, 76, 76));
        operation.setFont(new java.awt.Font("Agency FB", 0, 14)); // NOI18N
        operation.setForeground(new java.awt.Color(93, 76, 76));
        operation.setText("edit book");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel8.setText("Price");

        genreField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genreFieldActionPerformed(evt);
            }
        });
        genreField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                genreFieldKeyReleased(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel12.setText("Genre");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel9.setText("Shelf");

        shelField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shelFieldActionPerformed(evt);
            }
        });
        shelField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                shelFieldKeyReleased(evt);
            }
        });

        cancelButton.setBackground(new java.awt.Color(204, 204, 204));
        cancelButton.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 10)); // NOI18N
        cancelButton.setText("Cancel");
        cancelButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        priceField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                priceFieldKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                priceFieldKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout contentPanelLayout = new javax.swing.GroupLayout(contentPanel);
        contentPanel.setLayout(contentPanelLayout);
        contentPanelLayout.setHorizontalGroup(
            contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(authorField)
                    .addComponent(nameField)
                    .addComponent(serialField)
                    .addGroup(contentPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(cancelButton)
                        .addGap(18, 18, 18)
                        .addComponent(SaveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(contentPanelLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(operation))
                    .addComponent(genreField)
                    .addGroup(contentPanelLayout.createSequentialGroup()
                        .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(quantityField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                                .addComponent(sectField, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(jLabel6)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel5)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                        .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(shelField, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(priceField, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(contentPanelLayout.createSequentialGroup()
                        .addComponent(clearButton)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        contentPanelLayout.setVerticalGroup(
            contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentPanelLayout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(operation))
                .addGap(20, 20, 20)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(serialField, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(authorField, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(genreField, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sectField, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(shelField, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(quantityField, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(priceField, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SaveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(contentPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 510, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(contentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void quantityFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantityFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quantityFieldActionPerformed

    private void quantityFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_quantityFieldKeyReleased
         fieldSetBorder(quantityField, "number of books", 1);
      
    }//GEN-LAST:event_quantityFieldKeyReleased

    private void authorFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_authorFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_authorFieldActionPerformed

    private void authorFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_authorFieldKeyReleased
         fieldSetBorder(authorField, "author name", 3);
        
    }//GEN-LAST:event_authorFieldKeyReleased

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed

        serialField.setText(null);
        authorField.setText(null);
        nameField.setText(null);
        genreField.setText(null);
        sectField.setText(null);
        shelField.setText(null);
        quantityField.setText(null);
        priceField.setText(null);
    }//GEN-LAST:event_clearButtonActionPerformed

    private void SaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveButtonActionPerformed
        if (inventoryPage.serialAvailable(serialField.getText(),compId)) {
            JOptionPane.showMessageDialog(contentPanel, "serial number already exists");
        }else{
            if (operation.getText().equals("new book")) {
                System.err.println("save button");
                int x = inventoryPage.contentCompCount();
                bookPanel test = new bookPanel(
                    x+1+"",
                    serialField.getText(),
                    authorField.getText(),
                    nameField.getText(),
                    genreField.getText(),
                    sectField.getText(),
                    shelField.getText(),
                    (Object)quantityField.getText(),
                    priceField.getText());

                
                inventoryPage.addContentPanel(test);
                inventoryPage.updateBookId();
                contentPanel.updateUI();
                bookDialog.dispose();
            }else{
                //            JPanel user = (JPanel)contentPanel.getComponent(compId);

                bookPanel user = new bookPanel(
                    (compId+1)+"",
                    serialField.getText(),
                    authorField.getText(),
                    nameField.getText(),
                    genreField.getText(),
                    sectField.getText(),
                    shelField.getText(),
                    (Object)quantityField.getText(),
                    priceField.getText());
                
                inventoryPage.editContentPanel(compId,user);
                //            ((JLabel)user.getComponent(0)).setText(""+(i+1));
            }bookDialog.dispose();
            //
        
        }
    }//GEN-LAST:event_SaveButtonActionPerformed

    private void sectFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sectFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sectFieldActionPerformed

    private void sectFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sectFieldKeyReleased
        
        fieldSetBorder(sectField, "section", 1);
    }//GEN-LAST:event_sectFieldKeyReleased

    private void nameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameFieldActionPerformed

    private void nameFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameFieldKeyReleased
        fieldSetBorder(nameField, "book name", 3);
       
    }//GEN-LAST:event_nameFieldKeyReleased

    private void serialFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serialFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_serialFieldActionPerformed

    private void serialFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_serialFieldKeyReleased
        fieldSetBorder(serialField, "serial number", 5);
        
    }//GEN-LAST:event_serialFieldKeyReleased

    private void genreFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genreFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genreFieldActionPerformed

    private void genreFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_genreFieldKeyReleased
       fieldSetBorder(genreField, "genre", 3);
        
    }//GEN-LAST:event_genreFieldKeyReleased

    private void shelFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shelFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_shelFieldActionPerformed

    private void shelFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_shelFieldKeyReleased
        fieldSetBorder(shelField, "shelf number", 1);
       
    }//GEN-LAST:event_shelFieldKeyReleased

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        bookDialog.dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed
    
    private void quantityFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_quantityFieldKeyTyped
        char c = evt.getKeyChar();
        if (!((c >= '0') && (c <= '9') ||
           (c == KeyEvent.VK_BACK_SPACE) ||
           (c == KeyEvent.VK_DELETE))) {
          getToolkit().beep();
          evt.consume();
        }
    }//GEN-LAST:event_quantityFieldKeyTyped

    private void priceFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_priceFieldKeyTyped
         char c = evt.getKeyChar();
        if (!((c >= '0') && (c <= '9') ||
           (c == KeyEvent.VK_BACK_SPACE) ||
           (c == KeyEvent.VK_DELETE))) {
          getToolkit().beep();
          evt.consume();
        }
    }//GEN-LAST:event_priceFieldKeyTyped

    private void priceFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_priceFieldKeyReleased
        fieldSetBorder(priceField, "Book Price", 1);
    }//GEN-LAST:event_priceFieldKeyReleased

    public void fieldSetBorder(JTextField field,String name,int size){
        if (field.getText().length()<size) {
            field.setBorder(new LineBorder(Color.RED));
            field.setToolTipText("'"+name+"' must be atleast "+size);
            
        }else{
            field.setBorder(new LineBorder(Color.LIGHT_GRAY));
            field.setToolTipText(name);
        }
        dataFieldFilled();
    }
    
     public boolean dataFieldFilled(){
        if (serialField.getText().length()>=5&&
            authorField.getText().length()>=3&&
            nameField.getText().length()>=3&&
            genreField.getText().length()>=3&&
            sectField.getText().length()>=1&&
            shelField.getText().length()>=1&&
            quantityField.getText().length()>=1&&
            priceField.getText().length()>=1
            
            ){
               SaveButton.setEnabled(true);
               return true;
            
        }else{
            SaveButton.setEnabled(false);
            return false;
        }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SaveButton;
    private javax.swing.JTextField authorField;
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton clearButton;
    public static javax.swing.JPanel contentPanel;
    private javax.swing.JTextField genreField;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField nameField;
    private javax.swing.JLabel operation;
    private javax.swing.JFormattedTextField priceField;
    private javax.swing.JTextField quantityField;
    private javax.swing.JTextField sectField;
    private javax.swing.JTextField serialField;
    private javax.swing.JTextField shelField;
    // End of variables declaration//GEN-END:variables

    void setOperation(String operation) {
        this.operation.setText(operation);
    }
    String setOperation() {
        return operation.getText();
    }

    private void setSerialNo(String serialNo) {
        serialField.setText(serialNo);
    }

    private void setAuthor(String author) {
        authorField.setText(author);
    }

    private void setbookName(String bookName) {
        nameField.setText(bookName);
    }

    private void setGenre(String genre) {
        genreField.setText(genre);
    }

    private void setSection(String section) {
        sectField.setText(section);
    }

    private void setShelf(String shelf) {
        shelField.setText(shelf);
    }

    private void setQuantity(String no) {
        quantityField.setText(no);
    }

    private void setPrice(String price) {
        priceField.setText(price);
    }
}
